trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Figlet.csproj'
    zipAfterPublish: true
    modifyOutputPath: false
    arguments: '-c release -r win-x64 --self-contained true /p:PublishTrimmed=true --output $(System.ArtifactsDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.ArtifactsDirectory)'
    ArtifactName: 'Figlet'
    publishLocation: 'Container'